title: "Alex hjkl"
author: "Alexey Yashin"
description: "Notes about some tech stuff"

theme: minima 
include:
  - assets/css/style.scss

links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
