title: "Alex hjkl"
author:
  name: Alexey Yashin
#  email: aleksei.iashin91@gmail.com

description: "Notes about some tech stuff"
theme: minima 
links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
